name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  views:  # id of input
    description: 'number of milliseconds to wait'
    required: true
    default: 'day'
outputs:
  views: # output will be available to future steps
    description: 'page views'
runs:
  using: 'node12'
  main: 'dist/index.js'
