name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  # units:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: npm ci
  #   - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current repository name
      id: info
      uses: actions/github-script@v3.0.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          return await github.repos.getBranch({
            context.repo.owner,
            context.repo.repo,
            traffic,
          });

    # - name: Set traffic
    #   uses: ./
    #   with:
    #     views_per: day
    #     clones_per: week
    #     my_token: ${{ secrets.TRAFFIC_TOKEN }}

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_branch: traffic
    #     publish_dir: ./traffic
