name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  # units:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: npm ci
  #   - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set traffic
      uses: ./
      with:
        views_per: day
        clones_per: week
        my_token: ${{ secrets.TRAFFIC_TOKEN }}

    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_branch: traffic
    #     publish_dir: ./traffic
    #     user_name: 'github-actions[bot]'
    #     user_email: 'github-actions[bot]@users.noreply.github.com'
    #     full_commit_message: ${{ github.event.head_commit.message }}

    - name: Show traffic data
      run: |
        cd ./traffic/
        ls -a
